-- Migración Inicial: Tabla Demostración para Proyecto Agrícola
CREATE TABLE IF NOT EXISTS demostracion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  cultivo TEXT DEFAULT 'Maíz',
  humedad_suelo NUMERIC DEFAULT 65.5,
  temperatura NUMERIC DEFAULT 24.2,
  estado TEXT DEFAULT 'Activo'
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE demostracion ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso para la demo
DROP POLICY IF EXISTS "Permitir lectura publica" ON demostracion;
CREATE POLICY "Permitir lectura publica" ON demostracion FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir insercion publica" ON demostracion;
CREATE POLICY "Permitir insercion publica" ON demostracion FOR INSERT WITH CHECK (true);

-- Registros semilla
INSERT INTO demostracion (nombre, descripcion, cultivo, humedad_suelo, temperatura, estado)
SELECT 'Parcela Norte - Lote A', 'Sensor IoT de humedad y temperatura en zona alta', 'Aguacate Hass', 68.2, 22.4, 'Óptimo'
WHERE NOT EXISTS (SELECT 1 FROM demostracion LIMIT 1);

INSERT INTO demostracion (nombre, descripcion, cultivo, humedad_suelo, temperatura, estado)
SELECT 'Parcela Sur - Valle', 'Monitoreo de estrés hídrico con riego por goteo', 'Café Arábica', 61.5, 25.1, 'Riego programado'
WHERE (SELECT COUNT(*) FROM demostracion) = 1;

INSERT INTO demostracion (nombre, descripcion, cultivo, humedad_suelo, temperatura, estado)
SELECT 'Invernadero 1', 'Control climático automatizado y fertirriego', 'Tomate Saladette', 74.0, 21.8, 'Óptimo'
WHERE (SELECT COUNT(*) FROM demostracion) = 2;
